apiVersion: v1
kind: Service
metadata:
    name: {{ template "name" . }}
{{- if .Values.annotations }}
    annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
spec:
    ports:
      {{- range .Values.ports }}
      - name: {{ .name }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .Values.rcon.enabled }}
      - name: rcon
        port: {{ .Values.rcon.port }}
        targetPort: {{ .Values.rcon.port }}
      {{- end }}
    selector:
        app: {{ template "name" . }}