apiVersion: v1
kind: Service
metadata:
    name: {{ template "name" . }}
{{- if .Values.annotations }}
    annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
spec:
    ports:
      {{ range .Values.ports }}
      - name: {{ .name }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
      {{ end }}
    selector:
        app: {{ template "name" . }}