apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ template "name" . }}
    labels:
       app: {{ template "name" . }}
spec:
    selector:
        matchLabels:
            app: {{ template "name" . }}
    replicas: {{ .Values.replicas }}
    serviceName: {{ template "name" . }}
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
        spec:
            {{- if .Values.labels }}
            nodeSelector:
                {{- toYaml .Values.labels | nindent 16 }}
            {{- end }}

            containers:
              - name: server
                image: {{ .Values.image }}
                ports:
                  {{- range .Values.ports }}
                  - name: {{ .name }}
                    containerPort: {{ .targetPort }}
                  {{- end }}
                  {{- if or .Values.rcon.enabled .Values.backups.enabled }}
                  - name: rcon
                    containerPort: {{ .Values.rcon.port }}
                  {{- end }}
                envFrom:
                  - configMapRef:
                        name: {{ template "config-name" . }}
                volumeMounts:
                  - name: data
                    mountPath: /data
                resources:
                  requests:
                    memory: {{ .Values.mem }}
                    cpu: {{ .Values.cpu }}
                  limits:
                    memory: {{ .Values.mem_limit }}
                    cpu: {{ .Values.cpu_limit }}
              {{- if .Values.backups.enabled }}
              - name: backups
                image: itzg/mc-backup
                envFrom:
                  - configMapRef:
                      name: {{ template "backups-config" . }}
                env:
                  - name: SRC_DIR
                    value: /data
                  - name: DEST_DIR
                    value: /backups
                volumeMounts:
                  - name: data
                    mountPath: /data
                    readOnly: true
                  - name: backups
                    mountPath: /backups
              {{- end }}
            volumes:
              - name: data
                persistentVolumeClaim:
                    claimName: {{ template "data-pvc" . }}
              {{- if .Values.backups.enabled }}
              - name: backups
                persistentVolumeClaim:
                    claimName: {{ template "backups-pvc" . }}
              {{- end }}
