{{- if and .Values.data.enabled (not .Values.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ template "data-pvc" . }}
    annotations:
        helm.sh/resource-policy: keep
spec:
    {{- with .Values.data }}
    {{- if .storageClass }}
    storageClassName: {{ .storageClass | quote }}
    {{- end }}
    accessModes:
        - {{ .accessMode }}
    resources:
        requests:
            storage: {{ .storage | quote }}
    {{- end }}
{{- end }}
